[package]
name = "notnow"
version = "0.1.4"
authors = ["Daniel Mueller <deso@posteo.net>"]
license = "GPL-3.0+"
homepage = "https://github.com/d-e-s-o/notnow"
repository = "https://github.com/d-e-s-o/notnow.git"
readme = "README.md"
categories = ["command-line-utilities", "text-editors"]
keywords = ["TODO", "tasks", "planner"]
description = """
A terminal based task and TODO management software.
"""

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false
panic = "abort"

[features]
default = []
readline = ["rline"]

[dependencies.cell]
version = "0.1"

[dependencies.dirs]
version = "1.0"

[dependencies.gui]
version = "0.2"

[dependencies.gui-derive]
version = "0.2"

[dependencies.libc]
version = "0.2"

[dependencies.rline]
version = "0.1"
optional = true

[dependencies.serde]
version = "1.0"

[dependencies.serde_derive]
version = "1.0"

[dependencies.serde_json]
version = "1.0"

[dependencies.termion]
version = "1.5"

[dependencies.uid]
version = "0.1"
